### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by Yoinky3000**

### CODE REVIEW

**Comment by KevinNovak** [comment]
Thanks for this! I had been waiting for types!

**Comment by meister03** [comment]
Looks really good, will merge this after I have done a small update :)

**Comment by meister03** [comment]
This is a typo `[ket: string]` ?
fixed it, everything else seem to be correct

**Comment by meister03** [comment]
Should be live under `^2.1` 😄 
When you have any other requests feel free to dm me or open a issue...

**Pull request merged**
